/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shamim' at '4/13/17 5:48 PM' with Gradle 3.2
 *
 * @author shamim, @date 4/13/17 5:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
